### ISSUE TITLE
Uncaught Error: Class 'GuzzleAdapter' not found 

### ISSUE THREAD

**Issue by terrorfall** [wellcometrust/dotmailer-php#12]
Probably an issue from my side, but I'm getting the error

`Uncaught Error: Class 'GuzzleAdapter' not found `

When using the example given in the documentation. The autoload has been added to the PHP file

```
require 'vendor/autoload.php';

$adapter = GuzzleAdapter::fromCredentials('xxx', 'xxx');
$dotmailer = new Dotmailer($adapter);
$addressBooks = $dotmailer->getAddressBooks();

print_r($addressBooks);
```

Am I missing something?

Thanks

**Comment by amneale** [comment]
It looks to me like you're missing a couple of imports, you should have something like the following at the beginning of your code:

```
use Dotmailer\Adapter\GuzzleAdapter;
use Dotmailer\Dotmailer;
```

I'll update the documentation to reflect this, and to include the autoload as well!

**Comment by amneale** [comment]
@terrorfall the README has been updated, could you confirm if this fixes your issue?
